apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentinelone-secret
  namespace: sentinelone
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: sentinelone-vault-store
    kind: ClusterSecretStore
  target:
    name: sentinelone-secret
    creationPolicy: Owner
    template:
      data:
        SITE_KEY: "{{ .key }}"
  data:
    - secretKey: key
      remoteRef:
        key: prod
        property: key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentinelone-docker-secret
  namespace: sentinelone
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: sentinelone-vault-store
    kind: ClusterSecretStore
  target:
    name: sentinelone-docker-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.poc.mdplabs.dev": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: prod
        property: harbor-username
    - secretKey: password
      remoteRef:
        key: prod
        property: harbor-password
