apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-client
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
        - name: app-client
          image: placeholder/app-client:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-client-env
            - secretRef:
                name: app-client-secret
---
