namespace: internetbanking-dev

resources:
  - external-secret.yaml
  - ../../base
  
patchesStrategicMerge:
  - ingress-patch.yaml

configMapGenerator:
  - name: sdk-client-backend-env
    files:
      - sdk-client-backend.env

images:
  - name: placeholder/sdk-client-backend
    newName: harbor.poc.mdplabs.dev/internetbanking-middleware/sdk-client-backend
    newTag: dev-e2809fd8

replicas:
  - name: sdk-client-backend
    count: 1
