apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  dataFrom:
    - extract:
        key: postgres

