namespace: internetbanking-dev

resources:
  - external-secret.yaml
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yaml

configMapGenerator:
  - name: mdpus-client-env
    files:
      - mdpus-client.env

images:
  - name: placeholder/app-client
    newName: harbor.poc.mdplabs.dev/internetbanking-middleware/app-client
    newTag: dev-560c669c

replicas:
  - name: mdpus-client
    count: 1

