apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdk-client-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdk-client-backend
  template:
    metadata:
      labels:
        app: sdk-client-backend
    spec:
      containers:
        - name: sdk-client-backend
          image: placeholder/sdk-client-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: sdk-client-backend-env
            - secretRef:
                name: sdk-client-backend-secret
---
