apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 79.7.1
    helm:
      values: |
        prometheus:
          enabled: true
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn-replica2
                  resources:
                    requests:
                      storage: 8Gi

        kubelet:
          serviceMonitor:
            # relabelings:
            # - sourceLabels: [__address__]
            #   targetLabel: cluster
            #   replacement: "mdp-hetzner"
            #   action: replace
            additionalLabels::
             cluster: mdp-hetzner

        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik-external
            hosts:
              - grafana.poc.mdplabs.dev
            # annotations:
            #   cert-manager.io/cluster-issuer: acme-issuer
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.poc.mdplabs.dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
